name: qsu
description: >-
  qsu is a utility library that contains useful and frequently used functions. Start with your preferred language and the modern development environment.
version: 1.1.9
repository: https://github.com/jooy2/qsu
homepage: https://qsu.cdget.com

environment:
  sdk: ^3.5.0

dependencies:
  path: ^1.9.1
  crypto: ^3.0.7
  unorm_dart: ^0.3.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.15
